// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAjV1Nq4yTLrMIMm8GXuqDluU5HSXxxqE',
    appId: '1:331057366406:web:192926f88fe2a0586dd807',
    messagingSenderId: '331057366406',
    projectId: 'fir-assignment3-95df8',
    authDomain: 'fir-assignment3-95df8.firebaseapp.com',
    storageBucket: 'fir-assignment3-95df8.appspot.com',
    measurementId: 'G-QV5YR1PTLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6S3aiXOkVoikgmaZUEcQAsgQ8F7Uf9uw',
    appId: '1:331057366406:android:95be4442b857407f6dd807',
    messagingSenderId: '331057366406',
    projectId: 'fir-assignment3-95df8',
    storageBucket: 'fir-assignment3-95df8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt-FS0fZejoe5133WwutllMYJCwD1lVXs',
    appId: '1:331057366406:ios:7bb8d780472373d76dd807',
    messagingSenderId: '331057366406',
    projectId: 'fir-assignment3-95df8',
    storageBucket: 'fir-assignment3-95df8.appspot.com',
    iosBundleId: 'com.example.firebaseAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt-FS0fZejoe5133WwutllMYJCwD1lVXs',
    appId: '1:331057366406:ios:7bb8d780472373d76dd807',
    messagingSenderId: '331057366406',
    projectId: 'fir-assignment3-95df8',
    storageBucket: 'fir-assignment3-95df8.appspot.com',
    iosBundleId: 'com.example.firebaseAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAjV1Nq4yTLrMIMm8GXuqDluU5HSXxxqE',
    appId: '1:331057366406:web:cef94e2fc839b50c6dd807',
    messagingSenderId: '331057366406',
    projectId: 'fir-assignment3-95df8',
    authDomain: 'fir-assignment3-95df8.firebaseapp.com',
    storageBucket: 'fir-assignment3-95df8.appspot.com',
    measurementId: 'G-KLWCDWGZCT',
  );
}
